Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"

  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/xenial64"
	web01.vm.network "public_network"
    web01.vm.host_name = "websrv01"
	web01.vm.provider :virtualbox do |vb|
        vb.memory = 1024
        vb.cpus = 2
    end
	web01.vm.provision "shell", inline: <<-SHELL
    apt update 
	apt install apache2 wget unzip -y
	systemctl start apache2
	systemctl enable apache2
   SHELL
  end

  config.vm.define "db01" do |db01|
    db01.vm.box = "bento/centos-7.2"
	db01.vm.network "public_network"
	db01.vm.host_name = "dbsrv01"
    db01.vm.provider :virtualbox do |vb|
        vb.memory = 1024
        vb.cpus = 2
    end
	db01.vm.provision "shell", inline: <<-SHELL
    yum install mysql-server wget unzip -y
	systemctl start mysqld
	systemctl enable mysqld
   SHELL
  end
end