Vagrant.configure("2") do |config|
  config.vm.define "web001" do |web001|
    web001.vm.box = "ubuntu/trusty64"
	web001.vm.network "public_network"
    web001.vm.host_name = "websrv001"
	web001.vm.provider :virtualbox do |vb|
        vb.memory = 700
        vb.cpus = 1
    end
  end

  config.vm.define "db002" do |db002|
    db002.vm.box = "centos/7"
	db002.vm.network "public_network"
    db002.vm.host_name = "dbsrv001"	
	db002.vm.provider :virtualbox do |vb|
        vb.memory = 1024
        vb.cpus = 2
    end
  end
end